"""empty message

Revision ID: b7257089f313
Revises: b18ec9e3d44f
Create Date: 2021-07-31 10:06:59.602866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7257089f313'
down_revision = 'b18ec9e3d44f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comm_ques_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'question', ['comm_ques_id'], ['sno'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'comm_ques_id')
    # ### end Alembic commands ###
