"""Initial migration.

Revision ID: f10fcb90dfaf
Revises: 
Create Date: 2022-01-24 02:09:08.897830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f10fcb90dfaf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detail',
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('uid', sa.String(length=35), nullable=True),
    sa.Column('email', sa.String(length=25), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('location', sa.String(length=40), nullable=True),
    sa.Column('about', sa.String(length=3000), nullable=True),
    sa.Column('website_link', sa.String(length=50), nullable=True),
    sa.Column('twitter', sa.String(length=40), nullable=True),
    sa.Column('linkedin', sa.String(length=40), nullable=True),
    sa.Column('github_username', sa.String(length=40), nullable=True),
    sa.Column('pic', sa.String(length=30), nullable=True),
    sa.Column('date', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('question',
    sa.Column('sno', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('body', sa.String(length=80000), nullable=True),
    sa.Column('tag', sa.String(length=60), nullable=True),
    sa.Column('upvote', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=15), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['detail.username'], ),
    sa.PrimaryKeyConstraint('sno')
    )
    op.create_table('answers',
    sa.Column('ans_no', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=3000), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('real_answer', sa.String(length=5), nullable=True),
    sa.Column('date', sa.String(length=15), nullable=True),
    sa.Column('ques_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['ques_id'], ['question.sno'], ),
    sa.ForeignKeyConstraint(['username'], ['detail.username'], ),
    sa.PrimaryKeyConstraint('ans_no')
    )
    op.create_table('comments',
    sa.Column('comm_sno', sa.Integer(), nullable=False),
    sa.Column('sno', sa.Integer(), nullable=True),
    sa.Column('ques_sno', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('date', sa.String(length=15), nullable=True),
    sa.Column('comm_ans_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comm_ans_id'], ['answers.ans_no'], ),
    sa.ForeignKeyConstraint(['username'], ['detail.username'], ),
    sa.PrimaryKeyConstraint('comm_sno')
    )
    op.create_table('vote',
    sa.Column('sno', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('no', sa.Integer(), nullable=True),
    sa.Column('votetype', sa.String(length=10), nullable=True),
    sa.Column('aq_vote', sa.String(length=6), nullable=True),
    sa.Column('vote_ans_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['detail.username'], ),
    sa.ForeignKeyConstraint(['vote_ans_id'], ['answers.ans_no'], ),
    sa.PrimaryKeyConstraint('sno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_table('comments')
    op.drop_table('answers')
    op.drop_table('question')
    op.drop_table('detail')
    # ### end Alembic commands ###
